# Generated by Django 4.2.5 on 2023-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='nama_status',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
