# Generated by Django 4.2.5 on 2023-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_kategori_nama_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama_kategori',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='nama_produk',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='status',
            name='nama_status',
            field=models.CharField(),
        ),
    ]
